### ISSUE TITLE
`vault` throws an exception (TypeError: this._cipher.deriveKeys is not a function)

### ISSUE THREAD

**Issue by co-dan** [jcoglan/vault#36]
I have just downloaded the git version of `vault` to run on my machine. Running the executable produces the following error:

```
> vault test
/usr/local/lib/node_modules/vault/lib/loader.js:50
  this._cipher.deriveKeys(function(encryptionKey, signingKey) {
               ^

TypeError: this._cipher.deriveKeys is not a function
    at Loader.pathForService (/usr/local/lib/node_modules/vault/lib/loader.js:50:16)
    at Store.serviceSettings (/usr/local/lib/node_modules/vault/lib/store.js:219:16)
    at /usr/local/lib/node_modules/vault/node/composite_store.js:96:18
    at null.<anonymous> (/usr/local/lib/node_modules/vault/lib/store.js:132:14)
    at null.<anonymous> (/usr/local/lib/node_modules/vault/lib/loader.js:63:35)
    at ReadFileContext.callback (/usr/local/lib/node_modules/vault/node/file_adapter.js:22:32)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

I tried updated the `vault-cipher` submodule, but it didn't help.

**Comment by jcoglan** [comment]
I would not recommend actually using the `master` branch at present, I am in the process of overhauling how the storage backend works in preparation to release v0.4.

However, if you do want to look at `master`, can you tell me how you updated `vault-cipher`? Did you notice it's a submodule, not a normal npm install?

**Comment by co-dan** [comment]
> I would not recommend actually using the master branch at present, I am in the process of overhauling how the storage backend works in preparation to release v0.4.

Thanks. i've checked out the 0.3.0 version and it appears to be working fine.
The only reason I wanted to install `vault` from source is because on my system (Ubuntu), the name of the NodeJS interpreter is `nodejs`, not `node`.

> However, if you do want to look at master, can you tell me how you updated vault-cipher? Did you notice it's a submodule, not a normal npm install?

Yes, I updated it as a submodule to `master`

**Comment by jcoglan** [comment]
If you updated the submodule, I'm not sure why it's not working. However, the code in question is about to be completely removed once I have time to finish and commit the work I currently have in progress, so the next commit should make things more usable and hopefully a proper release will follow.

**Comment by jcoglan** [comment]
I should probably also mention that if you run the code currently on `master`, you will get config files that will stop working on the next release. Current `master` is a failed experiment that didn't work out and the backend storage code is being completely replaced in v0.4.

v0.4 will however attempt to migrate config files created by the v0.3 and possibly v0.2 release automatically. It's just the current `master` storage scheme that we won't be supporting long-term.
